name: plant_arvr
description: "A Flutter plant detection app using Gemini Vision."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.7
  ar_flutter_plugin: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



