name: plant_arvr
description: "A Flutter plant detection app using Gemini Vision."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  image_picker: ^1.1.2
  http: ^1.1.0
  camera: ^0.10.5
  permission_handler: ^10.4.5
  ar_flutter_plugin: ^0.7.3
  model_viewer_plus: ^1.7.0
  path_provider: ^2.1.1
  uuid: ^4.0.0
  arcore_flutter_plugin: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/3d/
